<?php

return [
    'paths' => [
        'pl' => [
            'offer_index' => 'oferta',
            'offer_dpf' => 'maszyny-do-dpf',
            'offer_workshop_washers' => 'myjki-warsztatowe',
            'offer_pressure_washers' => 'myjki-cisnieniowe',
            'chemia' => 'chemia',
            'custom_machines' => 'produkcja-maszyn',
            'new_products' => 'nowe-produkty',
            'about' => 'o-nas',
            'contact' => 'kontakt',
            'privacy' => 'polityka-prywatnosci',
            'blog_index' => 'blog',
            'blog_show' => 'blog/{slug}',
        ],
        'en' => [
            'offer_index' => 'offer',
            'offer_dpf' => 'dpf-machines',
            'offer_workshop_washers' => 'workshop-washers',
            'offer_pressure_washers' => 'pressure-washers',
            'chemia' => 'chemistry',
            'custom_machines' => 'custom-machine-production',
            'new_products' => 'new-product-lines',
            'about' => 'about',
            'contact' => 'contact',
            'privacy' => 'privacy',
            'blog_index' => 'blog',
            'blog_show' => 'blog/{slug}',
        ],
        'fr' => [
            'offer_index' => 'offre',
            'offer_dpf' => 'machines-dpf',
            'offer_workshop_washers' => 'laveuses-atelier',
            'offer_pressure_washers' => 'nettoyeurs-haute-pression',
            'chemia' => 'chimie',
            'custom_machines' => 'production-machines-sur-mesure',
            'new_products' => 'nouvelles-gammes',
            'about' => 'a-propos',
            'contact' => 'contact',
            'privacy' => 'politique-de-confidentialite',
            'blog_index' => 'actualites',
            'blog_show' => 'actualites/{slug}',
        ],
        'cz' => [
            'offer_index' => 'offer',
            'offer_dpf' => 'dpf-machines',
            'offer_workshop_washers' => 'workshop-washers',
            'offer_pressure_washers' => 'pressure-washers',
            'chemia' => 'chemistry',
            'custom_machines' => 'custom-machine-production',
            'new_products' => 'new-product-lines',
            'about' => 'about',
            'contact' => 'contact',
            'privacy' => 'privacy',
            'blog_index' => 'blog',
            'blog_show' => 'blog/{slug}',
        ],
        'de' => [
            'offer_index' => 'angebot',
            'offer_dpf' => 'dpf-maschinen',
            'offer_workshop_washers' => 'werkstattwaschanlagen',
            'offer_pressure_washers' => 'hochdruckreiniger',
            'chemia' => 'chemie',
            'custom_machines' => 'maschinenproduktion',
            'new_products' => 'neue-produktlinien',
            'about' => 'uber-uns',
            'contact' => 'kontakt',
            'privacy' => 'datenschutz',
            'blog_index' => 'blog',
            'blog_show' => 'blog/{slug}',
        ],
        'sk' => [
            'offer_index' => 'offer',
            'offer_dpf' => 'dpf-machines',
            'offer_workshop_washers' => 'workshop-washers',
            'offer_pressure_washers' => 'pressure-washers',
            'chemia' => 'chemistry',
            'custom_machines' => 'custom-machine-production',
            'new_products' => 'new-product-lines',
            'about' => 'about',
            'contact' => 'contact',
            'privacy' => 'privacy',
            'blog_index' => 'blog',
            'blog_show' => 'blog/{slug}',
        ],
        'hu' => [
            'offer_index' => 'offer',
            'offer_dpf' => 'dpf-machines',
            'offer_workshop_washers' => 'workshop-washers',
            'offer_pressure_washers' => 'pressure-washers',
            'chemia' => 'chemistry',
            'custom_machines' => 'custom-machine-production',
            'new_products' => 'new-product-lines',
            'about' => 'about',
            'contact' => 'contact',
            'privacy' => 'privacy',
            'blog_index' => 'blog',
            'blog_show' => 'blog/{slug}',
        ],
    ],
];
